name: Deploy MkDocs para o GitHub Pages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' 

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material  # Adicione outros plugins aqui, se necessário

    - name: Publicar no GitHub Pages
      run: mkdocs gh-deploy --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
